S3SourceConfigDef:
- 
  name: aws.access.key.id
  documentation: AWS Access Key ID
  type: PASSWORD
  default: null
  validValues: null, or a non empty String.
  importance: MEDIUM
- 
  name: aws.credentials.provider
  documentation: When you initialize a new service client without supplying any arguments, the AWS SDK for Java attempts to find temporary credentials by using the default credential provider chain implemented by the DefaultAWSCredentialsProviderChain class.
  type: CLASS
  default: class com.amazonaws.auth.DefaultAWSCredentialsProviderChain
  validValues: null
  importance: MEDIUM
- 
  name: aws.s3.backoff.delay.ms
  documentation: S3 default base sleep time for non-throttled exceptions in milliseconds. Default is 100.
  type: LONG
  default: 100
  validValues: [1,...]
  importance: MEDIUM
- 
  name: aws.s3.backoff.max.delay.ms
  documentation: S3 maximum back-off time before retrying a request in milliseconds. Default is 20000.
  type: LONG
  default: 20000
  validValues: [1,...]
  importance: MEDIUM
- 
  name: aws.s3.backoff.max.retries
  documentation: Maximum retry limit (if the value is greater than 30, there can be integer overflow issues during delay calculation). Default is 3.
  type: INT
  default: 3
  validValues: [1,...,30]
  importance: MEDIUM
- 
  name: aws.s3.bucket.name
  documentation: AWS S3 Bucket name
  type: STRING
  default: null
  validValues: Bucket name may not be null, may contain only the characters A-Z, a-z, 0-9, '-', '.', '_' must be between 3 and 63 characters long, must not be formatted as an IP Address, must not contain uppercase characters or white space, must not end with a period or a dash nor contains two adjacent periods, must not contain dashes next to periods nor begin with a dash
  importance: MEDIUM
- 
  name: aws.s3.endpoint
  documentation: Explicit AWS S3 Endpoint Address, mainly for testing
  type: STRING
  default: null
  validValues: A valid URL.  Will default to https protocol if not otherwise specified.
  importance: LOW
- 
  name: aws.s3.fetch.buffer.size
  documentation: AWS S3 Fetch buffer size, this is the number of s3object keys kept in a buffer to ensure lexically older objet keys aren't skipped for processing if they are slower to upload.
  type: INT
  default: 1000
  validValues: [1,...]
  importance: MEDIUM
- 
  name: aws.s3.fetch.page.size
  documentation: AWS S3 Fetch page size
  type: INT
  default: 10
  validValues: [1,...]
  importance: MEDIUM
- 
  name: aws.s3.prefix
  documentation: Prefix for stored objects, for example cluster-1/
  type: STRING
  default: null
  validValues: non-empty string
  importance: MEDIUM
- 
  name: aws.s3.region
  documentation: AWS S3 Region, for example us-east-1
  type: STRING
  default: null
  validValues: Supported values are: af-south-1, ap-east-1, ap-northeast-1, ap-northeast-2, ap-northeast-3, ap-south-1, ap-south-2, ap-southeast-1, ap-southeast-2, ap-southeast-3, ap-southeast-4, ca-central-1, ca-west-1, cn-north-1, cn-northwest-1, eu-central-1, eu-central-2, eu-north-1, eu-south-1, eu-south-2, eu-west-1, eu-west-2, eu-west-3, il-central-1, me-central-1, me-south-1, sa-east-1, us-east-1, us-east-2, us-gov-east-1, us-gov-west-1, us-iso-east-1, us-iso-west-1, us-isob-east-1, us-west-1, us-west-2
  importance: MEDIUM
- 
  name: aws.s3.sse.algorithm
  documentation: AWS S3 Server Side Encryption Algorithm. Example values: 'AES256', 'aws:kms'.
  type: STRING
  default: null
  validValues: non-empty string
  importance: MEDIUM
- 
  name: aws.secret.access.key
  documentation: AWS Secret Access Key
  type: PASSWORD
  default: null
  validValues: null, or a non empty String.
  importance: MEDIUM
- 
  name: aws.sts.config.endpoint
  documentation: AWS STS Config Endpoint
  type: STRING
  default: https://sts.amazonaws.com
  validValues: non-empty string
  importance: MEDIUM
- 
  name: aws.sts.role.arn
  documentation: AWS STS Role
  type: STRING
  default: null
  validValues: non-empty string
  importance: MEDIUM
- 
  name: aws.sts.role.external.id
  documentation: AWS STS External Id
  type: STRING
  default: null
  validValues: non-empty string
  importance: MEDIUM
- 
  name: aws.sts.role.session.duration
  documentation: AWS STS Session duration
  type: INT
  default: 3600
  validValues: [900,...,43200]
  importance: MEDIUM
- 
  name: aws.sts.role.session.name
  documentation: AWS STS Session name
  type: STRING
  default: null
  validValues: non-empty string
  importance: MEDIUM
- 
  name: aws_access_key_id
  documentation: AWS Access Key ID
  type: PASSWORD
  default: null
  validValues: null, or a non empty String.
  importance: MEDIUM
- 
  name: aws_s3_bucket
  documentation: AWS S3 Bucket name
  type: STRING
  default: null
  validValues: Bucket name may not be null, may contain only the characters A-Z, a-z, 0-9, '-', '.', '_' must be between 3 and 63 characters long, must not be formatted as an IP Address, must not contain uppercase characters or white space, must not end with a period or a dash nor contains two adjacent periods, must not contain dashes next to periods nor begin with a dash
  importance: MEDIUM
- 
  name: aws_s3_endpoint
  documentation: Explicit AWS S3 Endpoint Address, mainly for testing
  type: STRING
  default: null
  validValues: A valid URL.  Will default to https protocol if not otherwise specified.
  importance: LOW
- 
  name: aws_s3_prefix
  documentation: Prefix for stored objects, for example cluster-1/
  type: STRING
  default: null
  validValues: non-empty string
  importance: MEDIUM
- 
  name: aws_s3_region
  documentation: AWS S3 Region, for example us-east-1
  type: STRING
  default: null
  validValues: Supported values are: af-south-1, ap-east-1, ap-northeast-1, ap-northeast-2, ap-northeast-3, ap-south-1, ap-south-2, ap-southeast-1, ap-southeast-2, ap-southeast-3, ap-southeast-4, ca-central-1, ca-west-1, cn-north-1, cn-northwest-1, eu-central-1, eu-central-2, eu-north-1, eu-south-1, eu-south-2, eu-west-1, eu-west-2, eu-west-3, il-central-1, me-central-1, me-south-1, sa-east-1, us-east-1, us-east-2, us-gov-east-1, us-gov-west-1, us-iso-east-1, us-iso-west-1, us-isob-east-1, us-west-1, us-west-2
  importance: MEDIUM
- 
  name: aws_secret_access_key
  documentation: AWS Secret Access Key
  type: PASSWORD
  default: null
  validValues: null, or a non empty String.
  importance: MEDIUM
- 
  name: distribution.type
  documentation: Based on tasks.max config and the type of strategy selected, objects are processed in distributed way by Kafka connect workers, supported values : object_hash, partition
  type: STRING
  default: OBJECT_HASH
  validValues: Must be one of: [OBJECT_HASH, PARTITION]
  importance: MEDIUM
- 
  name: errors.tolerance
  documentation: Indicates to the connector what level of exceptions are allowed before the connector stops, supported values : none,all
  type: STRING
  default: NONE
  validValues: io.aiven.kafka.connect.common.config.SourceConfigFragment$ErrorsToleranceValidator@e60c516
  importance: MEDIUM
- 
  name: expected.max.message.bytes
  documentation: The largest record batch size allowed by Kafka config max.message.bytes
  type: INT
  default: 1048588
  validValues: null
  importance: MEDIUM
- 
  name: file.compression.type
  documentation: The compression type used for files put on S3. The supported values are: 'none', 'gzip', 'snappy', 'zstd'.
  type: STRING
  default: null
  validValues: Supported values are: 'none', 'gzip', 'snappy', 'zstd'
  importance: MEDIUM
- 
  name: file.max.records
  documentation: The maximum number of records to put in a single file. Must be a non-negative integer number. 0 is interpreted as "unlimited", which is the default.
  type: INT
  default: 0
  validValues: io.aiven.kafka.connect.common.config.FileNameFragment$1@7db4c883
  importance: MEDIUM
- 
  name: file.name.template
  documentation: The template for file names on S3. Supports `{{ variable }}` placeholders for substituting variables. Currently supported variables are `topic`, `partition`, and `start_offset` (the offset of the first record in the file). Only some combinations of variables are valid, which currently are:
- `topic`, `partition`, `start_offset`.There is also `key` only variable {{key}} for grouping by keys
  type: STRING
  default: null
  validValues: io.aiven.kafka.connect.common.config.validators.FilenameTemplateValidator@7158a28c
  importance: MEDIUM
- 
  name: file.name.timestamp.source
  documentation: Specifies the the timestamp variable source. Default is wall-clock.
  type: STRING
  default: WALLCLOCK
  validValues: io.aiven.kafka.connect.common.config.validators.TimestampSourceValidator@413fe58f
  importance: LOW
- 
  name: file.name.timestamp.timezone
  documentation: Specifies the timezone in which the dates and time for the timestamp variable will be treated. Use standard shot and long names. Default is UTC
  type: STRING
  default: Z
  validValues: io.aiven.kafka.connect.common.config.validators.TimeZoneValidator@49ffd0cb
  importance: LOW
- 
  name: format.output.envelope
  documentation: Whether to enable envelope for entries with single field.
  type: BOOLEAN
  default: true
  validValues: null
  importance: MEDIUM
- 
  name: format.output.fields
  documentation: Fields to put into output files. The supported values are: 'key', 'value', 'offset', 'timestamp', 'headers'.
  type: LIST
  default: [value]
  validValues: io.aiven.kafka.connect.common.config.validators.OutputFieldsValidator@1254e9a7
  importance: MEDIUM
- 
  name: format.output.fields.value.encoding
  documentation: The type of encoding for the value field. The supported values are: 'none', 'base64'.
  type: STRING
  default: base64
  validValues: io.aiven.kafka.connect.common.config.validators.OutputFieldsEncodingValidator@262c75a3
  importance: MEDIUM
- 
  name: format.output.type
  documentation: The format type of output content.
  type: STRING
  default: csv
  validValues: Supported values are: 'avro', 'csv', 'json', 'jsonl', 'parquet'
  importance: MEDIUM
- 
  name: input.format
  documentation: Input format of messages read from source avro/json/parquet/bytes
  type: STRING
  default: bytes
  validValues: non-empty string
  importance: MEDIUM
- 
  name: max.poll.records
  documentation: Max poll records
  type: INT
  default: 500
  validValues: [1,...]
  importance: MEDIUM
- 
  name: output_compression
  documentation: Output compression. Valid values are: gzip and none
  type: STRING
  default: null
  validValues: Supported values are: 'none', 'gzip', 'snappy', 'zstd'
  importance: MEDIUM
- 
  name: output_fields
  documentation: Output fields. A comma separated list of one or more: key, offset, timestamp, value, headers
  type: LIST
  default: null
  validValues: io.aiven.kafka.connect.config.s3.S3ConfigFragment$7@1881ef74
  importance: MEDIUM
- 
  name: schema.registry.url
  documentation: SCHEMA REGISTRY URL
  type: STRING
  default: null
  validValues: non-empty string
  importance: MEDIUM
- 
  name: topic
  documentation: eg : logging-topic
  type: STRING
  default: null
  validValues: non-empty string
  importance: MEDIUM
- 
  name: transformer.max.buffer.size
  documentation: Max Size of the byte buffer when using the BYTE Transformer
  type: INT
  default: 4096
  validValues: io.aiven.kafka.connect.common.config.TransformerFragment$ByteArrayTransformerMaxBufferSizeValidator@2fcf1d27
  importance: MEDIUM
- 
  name: value.converter.schema.registry.url
  documentation: SCHEMA REGISTRY URL
  type: STRING
  default: null
  validValues: non-empty string
  importance: MEDIUM
- 
  name: value.serializer
  documentation: Avro value serializer
  type: CLASS
  default: null
  validValues: null
  importance: MEDIUM
