# The workflow to check main after push.  Also used for badge on github site.
name: Latest pull request
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    uses: "./.github/workflows/general_build_workflow.yml"
