name: Publish Workflow
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: ''
jobs:
  publish:
    name: Publish v${{ github.event.inputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: v${{ github.event.inputs.tag }}
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and Publish with Gradle
        run: ./gradlew clean build bintrayUpload --debug
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          RELEASE_VERSION: ${{ github.event.inputs.tag }}
